{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ template "atlantis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlantis.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.extraAnnotations }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.extraAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "atlantis.name" . }}
      release: {{ .Release.Name }}
      {{- if .Values.podTemplate.labels }}
      {{- toYaml .Values.podTemplate.labels | nindent 6 }}
      {{- end }}
  endpoints:
  - port: atlantis
    {{- with .Values.podMonitor }}
    interval: {{ .interval }}
    {{- if .metricRelabeling }}
    metricRelabeling:
    {{- range .metricRelabeling }}
    - action: {{ default "replace" .action }}
      {{- if .regex }}
      # To ensure metrics are scraped correctly, we need to use >-
      # or keep the regex on a single line. If the regex is split across multiple lines,
      # it must be handled explicitly. Using toYaml will prevent the metrics from being scraped.
      regex: {{ .regex | replace "\n" "" | replace " " "" | quote }}
      {{- end }}
      {{- $extraParams := omit . "regex" "action" }}
      {{- if $extraParams }}
      {{- $extraParams | toYaml | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
